- name: Add Jenkins-CI Repository Key
  apt_key:
    url: "http://pkg.jenkins.io/{{ ansible_os_family|debian }}/jenkins.io.key"
    state: present

- name: Add Jenkins-CI Repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/{{ ansible_os_family|debian }} binary/'
    state: present
    update_cache: yes

- name: Install Jenkins-CI
  apt:
    name: jenkins
    state: present
    update_cache: yes
    cache_valid_time: 600
  notify:
    - Restart Jenkins
  register: install_jenkins

- 