- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Jenkins Debian package key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins Debian package repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present   