- name: Ensure SELinux is set to enforcing mode
  hosts: localhost
  tasks:
  - lineinfile:
      path: /home/ncs/shivansh notes/java-path-set.txt
      regexp: '^SELINUX='
      line: SELINUX= shivasnh